import os

GOOGLE_AI_API_KEY = os.getenv('GOOGLE_AI_API_KEY')
GOOGLE_AI_MODEL = os.getenv('GOOGLE_AI_MODEL')
GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
GOOGLE_BUCKET_NAME = os.getenv('GOOGLE_BUCKET_NAME')
